var assert = require("assert")
var good_enough_date_time = require('../good_enough_date_time.js')
var _ = require("underscore")

assert.equal(true, _.isEqual(["The", "quick", "brown", "fox"], good_enough_date_time.fancySplit("The.quick.brown.fox", ["."])))
var split2 = good_enough_date_time.fancySplit("The!quick.brown.fox", [".", "!"])
assert.equal(true, _.isEqual(["The", "quick", "brown", "fox"], split2), "split2 = "+split2)

var gedt1 = good_enough_date_time.LAST_MODIFIED_GOOD_ENOUGH_DATE_TIME_FORMAT.parseGoodEnoughDateTime("Mon, 18 May 2015 20:06:02 GMT")
assert.equal(false, gedt1.isUTC())
assert.equal("GMT", gedt1.getTimeZone())
assert.equal(2015, gedt1.getYear())
assert.equal(5, gedt1.getMonth())
assert.equal(18, gedt1.getDayOfMonth())
assert.equal(20, gedt1.getHour())
assert.equal(6, gedt1.getMinute())
assert.equal(2, gedt1.getSecond())
var strung1 = gedt1.toString()
assert.equal("2015-05-18T20:06:02 GMT", strung1)

var gedt2 = good_enough_date_time.LAST_MODIFIED_GOOD_ENOUGH_DATE_TIME_FORMAT.parseGoodEnoughDateTime("Tue, 02 Jun 2015 19:16:02 GMT")
assert.equal(false, gedt2.isUTC())
var strung2 = gedt2.toString()
assert.equal("2015-06-02T19:16:02 GMT", strung2)
assert.equal("2015-06-02 19:16:02 GMT", gedt2.casualFormat())

var gedt3 = good_enough_date_time.LAST_MODIFIED_GOOD_ENOUGH_DATE_TIME_FORMAT.parseGoodEnoughDateTime("Tue, 02 Jun 2015 19:16:02 UTC")
assert.equal(true, gedt3.isUTC())
var strung3 = gedt3.toString()
assert.equal("2015-06-02T19:16:02Z", strung3)
assert.equal("2015-06-02 19:16:02 UTC", gedt3.casualFormat())
